[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
engine = { path = "../engine" }
rust-stemmers = "1.2.0"
serde_json = "1.0.107"
time = "0.3.28"
